# === Stage 1 ===
FROM denoland/deno:alpine AS builder

WORKDIR /app

COPY . .

RUN deno cache main.ts

# === Stage 2 ===
FROM alpine:latest

RUN apk add --no-cache deno

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 8000

CMD ["deno", "run", "--allow-net", "--allow-read", "--allow-env", "--watch", "main.ts"]